#ifndef CANTICHEAT_HPP
#define CANTICHEAT_HPP
/*
* PASCAL GO LEARN C++ PLS FR
* ALSO LEARN HOW TO WRITE BYPASSES CUZ U SUCK FRRRRRRRRRRRRRRRRRRRRRRRRr
*/

namespace CAnti
{
    void StartAntiCheat();
}

#endif /* CANTICHEAT_HPP */
